### PR TITLE
Add translation to SwipeableItemProps

### PR DESCRIPTION
**Pull request by MikePodgorniy**
add origin translation node to renderLeadingItem/renderTrailingItem (SwipeableItemProps)

### CODE REVIEW

**Comment by iyegoroff** [comment]
Thanks for the contribution!

**Comment by MikePodgorniy** [comment]
oh.. I think "translation" cannot be optional, it's defined by default, can you check it?
translation?: Animated.Node<number>

**Comment by iyegoroff** [comment]
yes, '?' can be removed

**Comment by MikePodgorniy** [comment]
Do you have any plans to release the next version (npm package)?

**Comment by iyegoroff** [comment]
published v0.0.2

**Pull request merged**
